// Special characters (plan 09 task 9.6, issue #89): the bundled table behind
// the Insert > Special Characters popover. ~300 of the characters people
// actually insert, each with a searchable name — typing "copyright" finds ©,
// "arrow right" finds →. The popover renders the character glyphs directly,
// and the insert is the raw character as plain text (no markup, golden rule 1).
//
// Codepage safety (plan 09 AC5): the character is inserted into the document
// as a single UTF-8 code point. The save pipeline writes UTF-8 (the fs
// safety core is untouched), so a file that receives © stays valid UTF-8 on
// Windows and everywhere else — nothing here ever transcodes.
//
// "Recent" (plan 09 §2.5): the last-inserted characters, in insertion order
// (most recent first), persisted in localStorage like the find-panel position
// — a view convenience, never part of the document. The popover's first row.

export type SymbolCategory =
  | "currency"
  | "math"
  | "arrows"
  | "bullets"
  | "typography"
  | "symbols";

export interface SymbolCategorySpec {
  id: SymbolCategory;
  label: string;
}

// The six plan 09 §2.5 categories, in popover order.
export const SYMBOL_CATEGORIES: readonly SymbolCategorySpec[] = [
  { id: "currency", label: "Currency" },
  { id: "math", label: "Math" },
  { id: "arrows", label: "Arrows" },
  { id: "bullets", label: "Bullets" },
  { id: "typography", label: "Typography" },
  { id: "symbols", label: "Symbols" },
];

export function symbolCategoryById(id: string): SymbolCategorySpec | null {
  return SYMBOL_CATEGORIES.find((c) => c.id === id) ?? null;
}

export interface SymbolEntry {
  char: string;
  // The human name the popover searches ("copyright" → ©).
  name: string;
  category: SymbolCategory;
}

// The bundled table. One entry per character; the order inside a category is
// the popover's display order.
export const SYMBOLS: readonly SymbolEntry[] = [
  // --- Currency -----------------------------------------------------------
  { char: "$", name: "dollar sign", category: "currency" },
  { char: "¢", name: "cent sign", category: "currency" },
  { char: "£", name: "pound sign", category: "currency" },
  { char: "€", name: "euro sign", category: "currency" },
  { char: "¥", name: "yen sign", category: "currency" },
  { char: "₩", name: "won sign", category: "currency" },
  { char: "₣", name: "franc sign", category: "currency" },
  { char: "₤", name: "lira sign", category: "currency" },
  { char: "₦", name: "naira sign", category: "currency" },
  { char: "₧", name: "peseta sign", category: "currency" },
  { char: "₨", name: "rupee sign", category: "currency" },
  { char: "₪", name: "new sheqel sign", category: "currency" },
  { char: "₫", name: "dong sign", category: "currency" },
  { char: "₭", name: "kip sign", category: "currency" },
  { char: "₮", name: "tugrik sign", category: "currency" },
  { char: "₯", name: "drachma sign", category: "currency" },
  { char: "₰", name: "denarius sign", category: "currency" },
  { char: "₱", name: "peso sign", category: "currency" },
  { char: "₲", name: "guarani sign", category: "currency" },
  { char: "₳", name: "austral sign", category: "currency" },
  { char: "₴", name: "hryvnia sign", category: "currency" },
  { char: "₵", name: "cedi sign", category: "currency" },
  { char: "₶", name: "cordoba sign", category: "currency" },
  { char: "₷", name: "shilling sign", category: "currency" },
  { char: "₸", name: "tenge sign", category: "currency" },
  { char: "₹", name: "indian rupee sign", category: "currency" },
  { char: "₺", name: "turkish lira sign", category: "currency" },
  { char: "₻", name: "lat sign", category: "currency" },
  { char: "₼", name: "manat sign", category: "currency" },
  { char: "₽", name: "ruble sign", category: "currency" },
  { char: "₾", name: "lari sign", category: "currency" },
  { char: "₿", name: "bitcoin sign", category: "currency" },
  { char: "₡", name: "colon sign", category: "currency" },
  { char: "₢", name: "cruzeiro sign", category: "currency" },
  { char: "₥", name: "mill sign", category: "currency" },
  { char: "₠", name: "escudo sign", category: "currency" },
  { char: "ƒ", name: "florin", category: "currency" },

  // --- Math ---------------------------------------------------------------
  { char: "±", name: "plus-minus sign", category: "math" },
  { char: "∓", name: "minus-plus sign", category: "math" },
  { char: "×", name: "multiplication sign", category: "math" },
  { char: "÷", name: "division sign", category: "math" },
  { char: "+", name: "plus sign", category: "math" },
  { char: "−", name: "minus sign", category: "math" },
  { char: "=", name: "equals sign", category: "math" },
  { char: "≠", name: "not equal to", category: "math" },
  { char: "≈", name: "almost equal to", category: "math" },
  { char: "≅", name: "congruent to", category: "math" },
  { char: "≡", name: "identical to", category: "math" },
  { char: "<", name: "less-than sign", category: "math" },
  { char: "≤", name: "less-than or equal to", category: "math" },
  { char: ">", name: "greater-than sign", category: "math" },
  { char: "≥", name: "greater-than or equal to", category: "math" },
  { char: "≒", name: "wavy equal to", category: "math" },
  { char: "≓", name: "asymptotic to", category: "math" },
  { char: "≔", name: "defined as", category: "math" },
  { char: "≕", name: "delta equal to", category: "math" },
  { char: "≖", name: "proportional to", category: "math" },
  { char: "≜", name: "triple colon equals", category: "math" },
  { char: "≟", name: "question equal sign", category: "math" },
  { char: "≢", name: "not identical to", category: "math" },
  { char: "≣", name: "does not divide", category: "math" },
  { char: "≦", name: "less than over equal", category: "math" },
  { char: "≧", name: "greater than over equal", category: "math" },
  { char: "≨", name: "less than or approximate to", category: "math" },
  { char: "≩", name: "greater than or approximate to", category: "math" },
  { char: "≪", name: "much less than", category: "math" },
  { char: "≫", name: "much greater than", category: "math" },
  { char: "≌", name: "tilde equal to", category: "math" },
  { char: "≍", name: "all equal to", category: "math" },
  { char: "≎", name: "approaches the limit", category: "math" },
  { char: "≏", name: "proportionally", category: "math" },
  { char: "≐", name: "eventually equal to", category: "math" },
  { char: "≑", name: "double line equals", category: "math" },
  { char: "∂", name: "partial differential", category: "math" },
  { char: "∇", name: "nabla", category: "math" },
  { char: "∆", name: "increment", category: "math" },
  { char: "∏", name: "n-ary product", category: "math" },
  { char: "∑", name: "n-ary summation", category: "math" },
  { char: "√", name: "square root", category: "math" },
  { char: "∛", name: "cube root", category: "math" },
  { char: "∜", name: "fourth root", category: "math" },
  { char: "∫", name: "integral", category: "math" },
  { char: "∬", name: "double integral", category: "math" },
  { char: "∭", name: "triple integral", category: "math" },
  { char: "∮", name: "contour integral", category: "math" },
  { char: "∯", name: "surface integral", category: "math" },
  { char: "∰", name: "volume integral", category: "math" },
  { char: "∱", name: "clockwise integral", category: "math" },
  { char: "∲", name: "anticlockwise contour integral", category: "math" },
  { char: "∴", name: "therefore", category: "math" },
  { char: "∵", name: "because", category: "math" },
  { char: "∁", name: "complement", category: "math" },
  { char: "∄", name: "there does not exist", category: "math" },
  { char: "∃", name: "there exists", category: "math" },
  { char: "∅", name: "empty set", category: "math" },
  { char: "∝", name: "proportional symbol", category: "math" },
  { char: "∞", name: "infinity", category: "math" },
  { char: "∊", name: "element of", category: "math" },
  { char: "∋", name: "contains as member", category: "math" },
  { char: "∌", name: "does not contain as member", category: "math" },
  { char: "∍", name: "small element of", category: "math" },
  { char: "∎", name: "end of proof", category: "math" },
  { char: "∔", name: "plus sign above minus sign", category: "math" },
  { char: "∕", name: "division slash", category: "math" },
  { char: "∖", name: "set difference", category: "math" },
  { char: "∗", name: "asterisk operator", category: "math" },
  { char: "∘", name: "ring operator", category: "math" },
  { char: "°", name: "degree sign", category: "math" },
  { char: "′", name: "prime", category: "math" },
  { char: "″", name: "double prime", category: "math" },
  { char: "‴", name: "triple prime", category: "math" },
  // Greek letters
  { char: "α", name: "greek small alpha", category: "math" },
  { char: "β", name: "greek small beta", category: "math" },
  { char: "γ", name: "greek small gamma", category: "math" },
  { char: "δ", name: "greek small delta", category: "math" },
  { char: "ε", name: "greek small epsilon", category: "math" },
  { char: "ζ", name: "greek small zeta", category: "math" },
  { char: "η", name: "greek small eta", category: "math" },
  { char: "θ", name: "greek small theta", category: "math" },
  { char: "ι", name: "greek small iota", category: "math" },
  { char: "κ", name: "greek small kappa", category: "math" },
  { char: "λ", name: "greek small lambda", category: "math" },
  { char: "μ", name: "greek small mu", category: "math" },
  { char: "ν", name: "greek small nu", category: "math" },
  { char: "ξ", name: "greek small xi", category: "math" },
  { char: "ο", name: "greek small omicron", category: "math" },
  { char: "π", name: "pi", category: "math" },
  { char: "ρ", name: "greek small rho", category: "math" },
  { char: "σ", name: "greek small sigma", category: "math" },
  { char: "τ", name: "greek small tau", category: "math" },
  { char: "υ", name: "greek small upsilon", category: "math" },
  { char: "φ", name: "greek small phi", category: "math" },
  { char: "χ", name: "greek small chi", category: "math" },
  { char: "ψ", name: "greek small psi", category: "math" },
  { char: "ω", name: "greek small omega", category: "math" },
  { char: "Γ", name: "greek capital gamma", category: "math" },
  { char: "Δ", name: "greek capital delta", category: "math" },
  { char: "Θ", name: "greek capital theta", category: "math" },
  { char: "Λ", name: "greek capital lambda", category: "math" },
  { char: "Ξ", name: "greek capital xi", category: "math" },
  { char: "Π", name: "greek capital pi", category: "math" },
  { char: "Σ", name: "greek capital sigma", category: "math" },
  { char: "Φ", name: "greek capital phi", category: "math" },
  { char: "Ψ", name: "greek capital psi", category: "math" },
  { char: "Ω", name: "greek capital omega", category: "math" },
  // Superscripts and subscripts
  { char: "⁰", name: "superscript zero", category: "math" },
  { char: "¹", name: "superscript one", category: "math" },
  { char: "²", name: "superscript two", category: "math" },
  { char: "³", name: "superscript three", category: "math" },
  { char: "⁴", name: "superscript four", category: "math" },
  { char: "⁵", name: "superscript five", category: "math" },
  { char: "⁶", name: "superscript six", category: "math" },
  { char: "⁷", name: "superscript seven", category: "math" },
  { char: "⁸", name: "superscript eight", category: "math" },
  { char: "⁹", name: "superscript nine", category: "math" },
  { char: "⁺", name: "superscript plus", category: "math" },
  { char: "⁻", name: "superscript minus", category: "math" },
  { char: "⁼", name: "superscript equals", category: "math" },
  { char: "⁽", name: "superscript left parenthesis", category: "math" },
  { char: "⁾", name: "superscript right parenthesis", category: "math" },
  { char: "₀", name: "subscript zero", category: "math" },
  { char: "₁", name: "subscript one", category: "math" },
  { char: "₂", name: "subscript two", category: "math" },
  { char: "₃", name: "subscript three", category: "math" },
  { char: "₄", name: "subscript four", category: "math" },
  { char: "₅", name: "subscript five", category: "math" },
  { char: "₆", name: "subscript six", category: "math" },
  { char: "₇", name: "subscript seven", category: "math" },
  { char: "₈", name: "subscript eight", category: "math" },
  { char: "₉", name: "subscript nine", category: "math" },
  { char: "₊", name: "subscript plus", category: "math" },
  { char: "₋", name: "subscript minus", category: "math" },
  { char: "₌", name: "subscript equals", category: "math" },
  { char: "₍", name: "subscript left parenthesis", category: "math" },
  { char: "₎", name: "subscript right parenthesis", category: "math" },
  { char: "ⁿ", name: "superscript n", category: "math" },
  // Vulgar fractions
  { char: "½", name: "one half", category: "math" },
  { char: "⅓", name: "one third", category: "math" },
  { char: "⅔", name: "two thirds", category: "math" },
  { char: "¼", name: "one quarter", category: "math" },
  { char: "¾", name: "three quarters", category: "math" },
  { char: "⅛", name: "one eighth", category: "math" },
  { char: "⅜", name: "three eighths", category: "math" },
  { char: "⅝", name: "five eighths", category: "math" },
  { char: "⅞", name: "seven eighths", category: "math" },
  { char: "⅕", name: "one fifth", category: "math" },
  { char: "⅖", name: "two fifths", category: "math" },
  { char: "⅗", name: "three fifths", category: "math" },
  { char: "⅘", name: "four fifths", category: "math" },
  { char: "⅙", name: "one sixth", category: "math" },
  { char: "⅚", name: "five sixths", category: "math" },
  { char: "⅐", name: "one seventh", category: "math" },
  { char: "⅟", name: "one ninth", category: "math" },
  { char: "⅒", name: "one tenth", category: "math" },
  { char: "⁄", name: "fraction slash", category: "math" },
  // Set operations
  { char: "⊂", name: "subset of", category: "math" },
  { char: "⊃", name: "superset of", category: "math" },
  { char: "⊄", name: "not a subset of", category: "math" },
  { char: "⊅", name: "not a superset of", category: "math" },
  { char: "⊆", name: "subset of or equal to", category: "math" },
  { char: "⊇", name: "superset of or equal to", category: "math" },
  { char: "⊈", name: "not a subset of or equal to", category: "math" },
  { char: "⊉", name: "not a superset of or equal to", category: "math" },
  { char: "⊊", name: "proper subset of", category: "math" },
  { char: "⊋", name: "proper superset of", category: "math" },
  { char: "∩", name: "intersection", category: "math" },
  { char: "∪", name: "union", category: "math" },
  // Circled and squared operators
  { char: "⊕", name: "circled plus", category: "math" },
  { char: "⊖", name: "circled minus", category: "math" },
  { char: "⊗", name: "circled times", category: "math" },
  { char: "⊘", name: "circled division slash", category: "math" },
  { char: "⊙", name: "circled dot", category: "math" },
  { char: "⊚", name: "circled ring", category: "math" },
  { char: "⊛", name: "circled asterisk", category: "math" },
  { char: "⊞", name: "squared plus", category: "math" },
  { char: "⊟", name: "squared minus", category: "math" },
  { char: "⊠", name: "squared times", category: "math" },
  { char: "⊡", name: "squared plus sign", category: "math" },
  // Tacks and logic
  { char: "⊢", name: "right tack", category: "math" },
  { char: "⊣", name: "left tack", category: "math" },
  { char: "⊤", name: "down tack", category: "math" },
  { char: "⊥", name: "up tack", category: "math" },
  { char: "⊨", name: "models", category: "math" },
  { char: "⊩", name: "points to", category: "math" },
  { char: "⊬", name: "not provable", category: "math" },
  { char: "⊭", name: "not forces", category: "math" },
  { char: "⊮", name: "not true", category: "math" },
  { char: "⊲", name: "short right tack", category: "math" },
  { char: "⊳", name: "short left tack", category: "math" },
  { char: "⊴", name: "normal subset of", category: "math" },
  { char: "⊵", name: "contains as normal subset", category: "math" },
  { char: "∧", name: "logical and", category: "math" },
  { char: "∨", name: "logical or", category: "math" },
  { char: "⊻", name: "squared logical or", category: "math" },
  { char: "⊼", name: "squared logical nor", category: "math" },
  // --- Arrows ---------------------------------------------------------------
  { char: "←", name: "leftwards arrow", category: "arrows" },
  { char: "↑", name: "upwards arrow", category: "arrows" },
  { char: "→", name: "rightwards arrow", category: "arrows" },
  { char: "↓", name: "downwards arrow", category: "arrows" },
  { char: "↔", name: "left right arrow", category: "arrows" },
  { char: "↕", name: "up down arrow", category: "arrows" },
  { char: "↖", name: "north west arrow", category: "arrows" },
  { char: "↗", name: "north east arrow", category: "arrows" },
  { char: "↘", name: "south east arrow", category: "arrows" },
  { char: "↙", name: "south west arrow", category: "arrows" },
  { char: "↚", name: "leftwards arrow with stroke", category: "arrows" },
  { char: "↛", name: "rightwards arrow with stroke", category: "arrows" },
  { char: "↝", name: "leftwards arrow to bar", category: "arrows" },
  { char: "↞", name: "upwards arrow to bar", category: "arrows" },
  { char: "↠", name: "rightwards arrow to bar", category: "arrows" },
  { char: "↢", name: "leftwards white arrow", category: "arrows" },
  { char: "↣", name: "upwards white arrow", category: "arrows" },
  { char: "↤", name: "rightwards white arrow", category: "arrows" },
  { char: "↥", name: "downwards white arrow", category: "arrows" },
  { char: "↦", name: "mapped onto", category: "arrows" },
  { char: "↧", name: "down arrow bar", category: "arrows" },
  { char: "↩", name: "leftwards hook arrow", category: "arrows" },
  { char: "↪", name: "rightwards hook arrow", category: "arrows" },
  { char: "↫", name: "leftwards arrow with hook", category: "arrows" },
  { char: "↬", name: "rightwards arrow with hook", category: "arrows" },
  { char: "↭", name: "rightwards arrow with corner downwards", category: "arrows" },
  { char: "↮", name: "downwards arrow with corner leftwards", category: "arrows" },
  { char: "↯", name: "downwards zigzag arrow", category: "arrows" },
  { char: "↰", name: "upwards arrow with tip leftwards", category: "arrows" },
  { char: "↱", name: "upwards arrow with tip rightwards", category: "arrows" },
  { char: "↲", name: "leftwards arrow with tip upwards", category: "arrows" },
  { char: "↳", name: "rightwards arrow with tip upwards", category: "arrows" },
  { char: "↴", name: "leftwards arrow with tip downwards", category: "arrows" },
  { char: "↵", name: "return arrow", category: "arrows" },
  { char: "↶", name: "anticlockwise top semicircle arrow", category: "arrows" },
  { char: "↷", name: "clockwise top semicircle arrow", category: "arrows" },
  { char: "↸", name: "top arc from left to right", category: "arrows" },
  { char: "↹", name: "top arc from right to left", category: "arrows" },
  { char: "↺", name: "anticlockwise open circle arrow", category: "arrows" },
  { char: "↻", name: "clockwise open circle arrow", category: "arrows" },
  { char: "⇄", name: "right arrow left arrow", category: "arrows" },
  { char: "⇅", name: "up arrow down arrow", category: "arrows" },
  { char: "⇆", name: "leftwards arrow over rightwards arrow", category: "arrows" },
  { char: "⇇", name: "rightwards arrow over leftwards arrow", category: "arrows" },
  { char: "⇈", name: "upwards arrow leftwards of upwards arrow", category: "arrows" },
  { char: "⇉", name: "two rightwards arrows", category: "arrows" },
  { char: "⇊", name: "downwards arrow leftwards of downwards arrow", category: "arrows" },
  { char: "⇋", name: "leftwards pair with vertical bar", category: "arrows" },
  { char: "⇌", name: "rightwards arrow above leftwards arrow", category: "arrows" },
  { char: "⇍", name: "leftwards arrow above rightwards arrow", category: "arrows" },
  { char: "⇎", name: "leftwards harmonic arrow", category: "arrows" },
  { char: "⇏", name: "rightwards double arrow from bar", category: "arrows" },
  { char: "⇐", name: "leftwards double arrow", category: "arrows" },
  { char: "⇑", name: "upwards double arrow", category: "arrows" },
  { char: "⇒", name: "rightwards double arrow", category: "arrows" },
  { char: "⇓", name: "downwards double arrow", category: "arrows" },
  { char: "⇔", name: "left right double arrow", category: "arrows" },
  { char: "⇕", name: "up down double arrow", category: "arrows" },
  { char: "⇖", name: "north west double arrow", category: "arrows" },
  { char: "⇗", name: "north east double arrow", category: "arrows" },
  { char: "⇘", name: "south east double arrow", category: "arrows" },
  { char: "⇙", name: "south west double arrow", category: "arrows" },
  { char: "⇚", name: "leftwards double arrow with stroke", category: "arrows" },
  { char: "⇛", name: "rightwards double arrow with stroke", category: "arrows" },
  { char: "⇝", name: "rightwards two-headed arrow from bar", category: "arrows" },
  { char: "⇞", name: "upwards zigzag arrow", category: "arrows" },
  { char: "⇠", name: "leftwards dashed arrow", category: "arrows" },
  { char: "⇡", name: "upwards dashed arrow", category: "arrows" },
  { char: "⇢", name: "rightwards dashed arrow", category: "arrows" },
  { char: "⇣", name: "downwards dashed arrow", category: "arrows" },
  { char: "⇤", name: "leftwards arrow to bar with vertical bar", category: "arrows" },
  { char: "⇥", name: "rightwards arrow to bar with vertical bar", category: "arrows" },
  { char: "⇦", name: "leftwards double dashed arrow", category: "arrows" },
  { char: "⇧", name: "upwards double dashed arrow", category: "arrows" },
  { char: "⇨", name: "rightwards double dashed arrow", category: "arrows" },
  { char: "⇩", name: "downwards double dashed arrow", category: "arrows" },
  { char: "⇪", name: "upwards dagger arrow", category: "arrows" },
  { char: "⇫", name: "downwards dagger arrow", category: "arrows" },
  { char: "⇬", name: "leftwards closed arrow head", category: "arrows" },
  { char: "⇭", name: "upwards closed arrow head", category: "arrows" },
  { char: "⇮", name: "rightwards closed arrow head", category: "arrows" },
  { char: "⇯", name: "downwards closed arrow head", category: "arrows" },
  { char: "⇰", name: "leftwards triangle arrow head", category: "arrows" },
  { char: "⇱", name: "upwards triangle arrow head", category: "arrows" },
  { char: "⇲", name: "rightwards triangle arrow head", category: "arrows" },
  { char: "⇳", name: "downwards triangle arrow head", category: "arrows" },
  { char: "➔", name: "heavy rightwards arrow", category: "arrows" },
  { char: "➘", name: "heavy south east arrow", category: "arrows" },
  { char: "➝", name: "heavy rightwards arrow with circle", category: "arrows" },
  { char: "➟", name: "heavy rightwards arrow with triangle arrowhead", category: "arrows" },
  // --- Bullets ---------------------------------------------------------------
  { char: "•", name: "bullet", category: "bullets" },
  { char: "‣", name: "triangular bullet", category: "bullets" },
  { char: "⁃", name: "hyphenation bullet", category: "bullets" },
  { char: "∙", name: "dot operator", category: "bullets" },
  { char: "◦", name: "white bullet", category: "bullets" },
  { char: "‒", name: "figure dash", category: "bullets" },
  { char: "–", name: "en dash", category: "bullets" },
  { char: "—", name: "em dash", category: "bullets" },
  { char: "―", name: "horizontal bar", category: "bullets" },
  { char: "⸺", name: "em dash with low line", category: "bullets" },
  { char: "⸻", name: "two em dash", category: "bullets" },
  { char: "·", name: "middle dot", category: "bullets" },
  { char: "‸", name: "raised middle dot", category: "bullets" },
  { char: "▪", name: "small black square", category: "bullets" },
  { char: "▫", name: "white small square", category: "bullets" },
  { char: "□", name: "white square", category: "bullets" },
  { char: "■", name: "black square", category: "bullets" },
  { char: "▭", name: "white rectangle", category: "bullets" },
  { char: "▮", name: "black vertical rectangle", category: "bullets" },
  { char: "▯", name: "white vertical rectangle", category: "bullets" },
  { char: "▸", name: "small black right-pointing triangle", category: "bullets" },
  { char: "▹", name: "black right-pointing small triangle", category: "bullets" },
  { char: "◄", name: "black left-pointing pointer", category: "bullets" },
  { char: "►", name: "black right-pointing pointer", category: "bullets" },
  { char: "◀", name: "black left-pointing triangle", category: "bullets" },
  { char: "▶", name: "black right-pointing triangle", category: "bullets" },
  { char: "△", name: "white up-pointing triangle", category: "bullets" },
  { char: "▲", name: "black up-pointing triangle", category: "bullets" },
  { char: "▽", name: "white down-pointing triangle", category: "bullets" },
  { char: "▼", name: "black down-pointing triangle", category: "bullets" },
  { char: "◁", name: "white left-pointing triangle", category: "bullets" },
  { char: "▷", name: "white right-pointing triangle", category: "bullets" },
  { char: "○", name: "white circle", category: "bullets" },
  { char: "●", name: "black circle", category: "bullets" },
  { char: "◐", name: "circle with left half black", category: "bullets" },
  { char: "◑", name: "circle with right half black", category: "bullets" },
  { char: "◒", name: "circle with lower half black", category: "bullets" },
  { char: "◓", name: "circle with upper half black", category: "bullets" },
  { char: "◕", name: "circle with all but upper left quadrant black", category: "bullets" },
  { char: "◎", name: "bullseye", category: "bullets" },
  { char: "◌", name: "dotted circle", category: "bullets" },
  { char: "◍", name: "dotted circle with filling", category: "bullets" },
  // --- Typography ------------------------------------------------------------
  { char: "«", name: "left guillemet", category: "typography" },
  { char: "»", name: "right guillemet", category: "typography" },
  { char: "‹", name: "single left guillemet", category: "typography" },
  { char: "›", name: "single right guillemet", category: "typography" },
  { char: "‚", name: "single low-9 quotation mark", category: "typography" },
  { char: "„", name: "double low-9 quotation mark", category: "typography" },
  { char: "‛", name: "single high reversed-9 quotation mark", category: "typography" },
  { char: "‟", name: "double high reversed-9 quotation mark", category: "typography" },
  { char: "‘", name: "left single quotation mark", category: "typography" },
  { char: "’", name: "right single quotation mark", category: "typography" },
  { char: "“", name: "left double quotation mark", category: "typography" },
  { char: "”", name: "right double quotation mark", category: "typography" },
  { char: "…", name: "horizontal ellipsis", category: "typography" },
  { char: "†", name: "dagger", category: "typography" },
  { char: "‡", name: "double dagger", category: "typography" },
  { char: "‼", name: "twin exclamation marks", category: "typography" },
  { char: "⁉", name: "exclamation question mark", category: "typography" },
  { char: "‽", name: "interrobang", category: "typography" },
  { char: "§", name: "section sign", category: "typography" },
  { char: "¶", name: "pilcrow sign", category: "typography" },
  { char: "©", name: "copyright sign", category: "typography" },
  { char: "®", name: "registered sign", category: "typography" },
  { char: "™", name: "trade mark sign", category: "typography" },
  { char: "№", name: "number sign", category: "typography" },
  { char: "℅", name: "care of", category: "typography" },
  { char: "µ", name: "micro sign", category: "typography" },
  { char: "º", name: "masculine ordinal indicator", category: "typography" },
  { char: "ª", name: "feminine ordinal indicator", category: "typography" },
  { char: "¿", name: "inverted question mark", category: "typography" },
  { char: "¡", name: "inverted exclamation mark", category: "typography" },
  { char: "¦", name: "broken bar", category: "typography" },
  { char: "¬", name: "not sign", category: "typography" },
  { char: "¯", name: "macron", category: "typography" },
  { char: "ˉ", name: "macron symbol", category: "typography" },
  { char: "¨", name: "diaeresis", category: "typography" },
  { char: "˚", name: "ring above", category: "typography" },
  { char: "˛", name: "ogonek", category: "typography" },
  { char: "˜", name: "small tilde", category: "typography" },
  { char: "˘", name: "breve", category: "typography" },
  { char: "˙", name: "dot above", category: "typography" },
  { char: "˝", name: "double acute accent", category: "typography" },
  { char: "¸", name: "cedilla", category: "typography" },
  { char: "ß", name: "sharp s", category: "typography" },
  { char: "æ", name: "ae ligature", category: "typography" },
  { char: "Æ", name: "capital ae ligature", category: "typography" },
  { char: "œ", name: "oe ligature", category: "typography" },
  { char: "Œ", name: "capital oe ligature", category: "typography" },
  { char: "à", name: "a grave", category: "typography" },
  { char: "á", name: "a acute", category: "typography" },
  { char: "â", name: "a circumflex", category: "typography" },
  { char: "ã", name: "a tilde", category: "typography" },
  { char: "ä", name: "a diaeresis", category: "typography" },
  { char: "å", name: "a ring above", category: "typography" },
  { char: "è", name: "e grave", category: "typography" },
  { char: "é", name: "e acute", category: "typography" },
  { char: "ê", name: "e circumflex", category: "typography" },
  { char: "ë", name: "e diaeresis", category: "typography" },
  { char: "ì", name: "i grave", category: "typography" },
  { char: "í", name: "i acute", category: "typography" },
  { char: "î", name: "i circumflex", category: "typography" },
  { char: "ï", name: "i diaeresis", category: "typography" },
  { char: "ñ", name: "n tilde", category: "typography" },
  { char: "ò", name: "o grave", category: "typography" },
  { char: "ó", name: "o acute", category: "typography" },
  { char: "ô", name: "o circumflex", category: "typography" },
  { char: "õ", name: "o tilde", category: "typography" },
  { char: "ö", name: "o diaeresis", category: "typography" },
  { char: "ù", name: "u grave", category: "typography" },
  { char: "ú", name: "u acute", category: "typography" },
  { char: "û", name: "u circumflex", category: "typography" },
  { char: "ü", name: "u diaeresis", category: "typography" },
  { char: "ý", name: "y acute", category: "typography" },
  { char: "ÿ", name: "y diaeresis", category: "typography" },
  { char: "Å", name: "angstrom sign", category: "typography" },
  { char: "℃", name: "degree celsius", category: "typography" },
  { char: "℉", name: "degree fahrenheit", category: "typography" },
  { char: "ℓ", name: "script small l", category: "typography" },
  { char: "ℏ", name: "planck constant over two pi", category: "typography" },
  { char: "℘", name: "weierstrass p", category: "typography" },
  { char: "ℑ", name: "script capital i", category: "typography" },
  { char: "ℛ", name: "script capital r", category: "typography" },
  { char: "ℵ", name: "alef symbol", category: "typography" },
  { char: "ℶ", name: "bet symbol", category: "typography" },
  { char: "ℨ", name: "black-letter capital z", category: "typography" },
  { char: "℧", name: "inverse ohm", category: "typography" },
  // --- Symbols ----------------------------------------------------------------
  { char: "♠", name: "spade suit", category: "symbols" },
  { char: "♣", name: "club suit", category: "symbols" },
  { char: "♥", name: "heart suit", category: "symbols" },
  { char: "♦", name: "diamond suit", category: "symbols" },
  { char: "♩", name: "eighth note", category: "symbols" },
  { char: "♪", name: "quarter note", category: "symbols" },
  { char: "♫", name: "beamed eighth notes", category: "symbols" },
  { char: "♬", name: "beamed sixteenth notes", category: "symbols" },
  { char: "☀", name: "white sun with rays", category: "symbols" },
  { char: "☁", name: "cloud", category: "symbols" },
  { char: "☂", name: "umbrella", category: "symbols" },
  { char: "☃", name: "snowman", category: "symbols" },
  { char: "☎", name: "black telephone", category: "symbols" },
  { char: "☐", name: "ballot box", category: "symbols" },
  { char: "☑", name: "ballot box with check", category: "symbols" },
  { char: "☒", name: "ballot box with x", category: "symbols" },
  { char: "☕", name: "hot beverage", category: "symbols" },
  { char: "☘", name: "four leaf clover", category: "symbols" },
  { char: "☮", name: "peace symbol", category: "symbols" },
  { char: "☯", name: "yin yang", category: "symbols" },
  { char: "☸", name: "wheel of dharma", category: "symbols" },
  { char: "☹", name: "white frowning face", category: "symbols" },
  { char: "☺", name: "white smiling face", category: "symbols" },
  { char: "☻", name: "black smiling face", category: "symbols" },
  { char: "☼", name: "white sun with black outline", category: "symbols" },
  { char: "☽", name: "first quarter moon", category: "symbols" },
  { char: "☾", name: "last quarter moon", category: "symbols" },
  { char: "☿", name: "mercury symbol", category: "symbols" },
  { char: "♀", name: "female sign", category: "symbols" },
  { char: "♂", name: "male sign", category: "symbols" },
  { char: "♃", name: "jupiter symbol", category: "symbols" },
  { char: "♄", name: "saturn symbol", category: "symbols" },
  { char: "♅", name: "uranus symbol", category: "symbols" },
  { char: "♆", name: "neptune symbol", category: "symbols" },
  { char: "♇", name: "pluto symbol", category: "symbols" },
  // Zodiac
  { char: "♈", name: "aries symbol", category: "symbols" },
  { char: "♉", name: "taurus symbol", category: "symbols" },
  { char: "♊", name: "gemini symbol", category: "symbols" },
  { char: "♋", name: "cancer symbol", category: "symbols" },
  { char: "♌", name: "leo symbol", category: "symbols" },
  { char: "♍", name: "virgo symbol", category: "symbols" },
  { char: "♎", name: "libra symbol", category: "symbols" },
  { char: "♏", name: "scorpio symbol", category: "symbols" },
  { char: "♐", name: "sagittarius symbol", category: "symbols" },
  { char: "♑", name: "capricorn symbol", category: "symbols" },
  { char: "♒", name: "aquarius symbol", category: "symbols" },
  { char: "♓", name: "pisces symbol", category: "symbols" },
  // Chess
  { char: "♔", name: "white chess king", category: "symbols" },
  { char: "♕", name: "white chess queen", category: "symbols" },
  { char: "♖", name: "white chess rook", category: "symbols" },
  { char: "♗", name: "white chess bishop", category: "symbols" },
  { char: "♘", name: "white chess knight", category: "symbols" },
  { char: "♙", name: "white chess pawn", category: "symbols" },
  { char: "♚", name: "black chess king", category: "symbols" },
  { char: "♛", name: "black chess queen", category: "symbols" },
  { char: "♜", name: "black chess rook", category: "symbols" },
  { char: "♝", name: "black chess bishop", category: "symbols" },
  { char: "♞", name: "black chess knight", category: "symbols" },
  { char: "♟", name: "black chess pawn", category: "symbols" },
  // Misc
  { char: "⚀", name: "die face one", category: "symbols" },
  { char: "⚁", name: "die face two", category: "symbols" },
  { char: "⚂", name: "die face three", category: "symbols" },
  { char: "⚃", name: "die face four", category: "symbols" },
  { char: "⚄", name: "die face five", category: "symbols" },
  { char: "⚅", name: "die face six", category: "symbols" },
  { char: "⚖", name: "scales", category: "symbols" },
  { char: "⚗", name: "alembic", category: "symbols" },
  { char: "⚘", name: "flower", category: "symbols" },
  { char: "⚙", name: "gear", category: "symbols" },
  { char: "⚚", name: "staff of aesculapius", category: "symbols" },
  { char: "⚛", name: "atom symbol", category: "symbols" },
  { char: "⚜", name: "fleur-de-lis", category: "symbols" },
  { char: "⚝", name: "star of david", category: "symbols" },
  { char: "⚞", name: "six pointed black star", category: "symbols" },
  { char: "⚟", name: "sparkle", category: "symbols" },
  { char: "⚠", name: "warning sign", category: "symbols" },
  { char: "⚡", name: "high voltage sign", category: "symbols" },
  { char: "⚫", name: "medium black circle", category: "symbols" },
  { char: "⚪", name: "medium white circle", category: "symbols" },
  { char: "⚰", name: "coffin", category: "symbols" },
  { char: "⚱", name: "funeral urn", category: "symbols" },
  { char: "☠", name: "skull and crossbones", category: "symbols" },
  { char: "☢", name: "radioactive sign", category: "symbols" },
  { char: "☣", name: "biohazard sign", category: "symbols" },
  { char: "☦", name: "orthodox cross", category: "symbols" },
  { char: "☨", name: "cross of lorraine", category: "symbols" },
  { char: "☪", name: "star and crescent", category: "symbols" },
  // Dingbats
  { char: "✂", name: "black scissors", category: "symbols" },
  { char: "✈", name: "airplane", category: "symbols" },
  { char: "✉", name: "envelope", category: "symbols" },
  { char: "✎", name: "pencil", category: "symbols" },
  { char: "✏", name: "black pencil", category: "symbols" },
  { char: "✒", name: "black nib", category: "symbols" },
  { char: "✓", name: "check mark", category: "symbols" },
  { char: "✔", name: "heavy check mark", category: "symbols" },
  { char: "✕", name: "multiplication x", category: "symbols" },
  { char: "✖", name: "heavy multiplication x", category: "symbols" },
  { char: "✗", name: "ballot x", category: "symbols" },
  { char: "✘", name: "heavy ballot x", category: "symbols" },
  { char: "✦", name: "black four pointed star", category: "symbols" },
  { char: "✧", name: "white four pointed star", category: "symbols" },
  { char: "❤", name: "black heart", category: "symbols" },
  { char: "❄", name: "snowflake", category: "symbols" },
  { char: "❅", name: "tilted heavy snowflake", category: "symbols" },
  { char: "❆", name: "heavy snowflake", category: "symbols" },
  { char: "❇", name: "six point sparkle", category: "symbols" },
  { char: "❈", name: "open centre eight pointed star", category: "symbols" },
  { char: "❉", name: "eight spoked asterisk", category: "symbols" },
  { char: "❊", name: "eight pointed black star", category: "symbols" },
  { char: "❋", name: "eight pointed rectangle black star", category: "symbols" },
  { char: "❍", name: "circled open centre eight pointed star", category: "symbols" },
  { char: "❓", name: "heavy question mark", category: "symbols" },
  { char: "❔", name: "heavy exclamation mark", category: "symbols" },
  { char: "❕", name: "exclamation mark symbol", category: "symbols" },
  { char: "❗", name: "heavy exclamation mark symbol", category: "symbols" },
  { char: "❘", name: "light vertical bar", category: "symbols" },
  { char: "❙", name: "medium vertical bar", category: "symbols" },
  { char: "❚", name: "heavy vertical bar", category: "symbols" },
  { char: "❮", name: "left-pointing angle bracket ornament", category: "symbols" },
  { char: "❯", name: "right-pointing angle bracket ornament", category: "symbols" },
  { char: "❰", name: "left-pointing triangular ornament", category: "symbols" },
  { char: "❱", name: "right-pointing triangular ornament", category: "symbols" },
  { char: "➙", name: "heavier round-tipped rightwards arrow", category: "symbols" },
  { char: "➚", name: "heavy north east arrow", category: "symbols" },
  { char: "➜", name: "heavy round-tipped rightwards arrow", category: "symbols" },
  { char: "➡", name: "heavy black rightwards arrow", category: "symbols" },
  { char: "➤", name: "black rightwards arrowhead", category: "symbols" },
  { char: "➥", name: "heavy rightwards arrow from bar", category: "symbols" },
  { char: "➦", name: "heavy rightwards arrow to bar", category: "symbols" },
  { char: "➩", name: "heavy round-tipped rightwards arrow with double stroke", category: "symbols" },
  { char: "➰", name: "curly loop", category: "symbols" },
  { char: "➱", name: "loopy loop", category: "symbols" },
  { char: "➲", name: "curled tail", category: "symbols" },
  { char: "➳", name: "curled tail with vertical bar", category: "symbols" },
  { char: "➴", name: "curled tail with down arrow", category: "symbols" },
  { char: "➵", name: "loopy preceding curly loop", category: "symbols" },
];

// All entries whose name contains `query` (case-insensitive), in table order.
// An empty query returns the whole table.
export function searchSymbols(query: string): SymbolEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [...SYMBOLS];
  return SYMBOLS.filter((s) => s.name.toLowerCase().includes(q));
}

// The entries of one category, in table order.
export function symbolsInCategory(category: SymbolCategory): SymbolEntry[] {
  return SYMBOLS.filter((s) => s.category === category);
}

// The whole table, one entry per character (the popover dedupes by character
// when merging recents with the filtered table).
export const SYMBOL_COUNT = SYMBOLS.length;

// ---------------------------------------------------------------------------
// Recent characters
// ---------------------------------------------------------------------------

const RECENT_STORAGE_KEY = "quillmd.symbols.recent";
const RECENT_MAX = 24;

function readRecentRaw(): string[] {
  try {
    const raw = globalThis.localStorage?.getItem(RECENT_STORAGE_KEY);
    if (!raw) return [];
    const parsed: unknown = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [];
    return parsed.filter(
      (c): c is string =>
        typeof c === "string" && c.length > 0 && [...c].length === 1,
    );
  } catch {
    return [];
  }
}

// The recent characters, most recent first (max RECENT_MAX, deduplicated).
export function getRecentSymbols(): string[] {
  return readRecentRaw().slice(0, RECENT_MAX);
}

// Records an insert: moves `char` to the front, deduplicates, truncates.
// No-op if the character is empty.
export function recordSymbolInsert(char: string): string[] {
  if (!char || [...char].length !== 1) return getRecentSymbols();
  const next = [char, ...getRecentSymbols().filter((c) => c !== char)].slice(
    0,
    RECENT_MAX,
  );
  try {
    globalThis.localStorage?.setItem(RECENT_STORAGE_KEY, JSON.stringify(next));
  } catch {
    // localStorage unavailable (private mode, quota) — recent is a
    // convenience, not correctness.
  }
  return next;
}
